server:
  port: 20000

spring:
  application:
    name: gulimall-auth
  profiles:
    active: dev
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        namespace: fa8ae864-e1c1-4a62-b82c-1b9c7ffe1a4d
        file-extension: yml
