spring:
  cloud:
    alicloud:
      access-key: your access-key
      secret-key: your secret-key
      oss:
        bucket: your bucket name
        endpoint: xxx.com
      sms:
        host: https://xxx.com
        path: /xxx
        appCode: your appCode